# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kf7ezh1py8mMQyVfZ23gnbF_G5j_SKbl
"""

def tashxis(belgi):
 if belgi== "istima" :
  return "Parasetamol iching"
 elif belgi== "katarakta":
  return "Deksamitazon"
 elif belgi== "bosh og'rig'i":
  return "Trimol"
 elif belgi=="gripp":
  return "Taylolhot"
 else:
  return "Shifokorga murojaat giling"
belgi=input("kasallik belgisini kiriting'")
natija=tashxis(belgi)
print (natija)

def tashxis(belgi):
 if belgi== " iphone 11pro" :
  return "narxi 300$"
 elif belgi== "iphone 12pro":
  return "430$"
 elif belgi== "iphone 13pro":
  return "550$"
 else:
  return "Adminga murojat qiling"
belgi=input("Iphone rusumi")
natija=tashxis(belgi)
print (natija)

from google.colab.patches import cv2_imshow
import cv2
def narxi(rusumi):
 if rusumi=="iphone11pro" :
   rasm=cv2.imread("11pro.webp")
   cv2_imshow(rasm)
   return "narxi 300$"
 elif rusumi=="iphone12pro":
   rasm=cv2.imread("12pro.webp")
   cv2_imshow(rasm1)
   return "narxi 420$"
 elif rusumi=="iphone13pro":
   rasm=cv2.imread("13pro.webp")
   cv2_imshow(rasm)
   return "narxi 550$"
 elif rusumi=="iphone16":
   rasm=cv2.imread("16.webp")
   cv2_imshow(rasm)
   return "narxi 1200$"
 elif rusumi=="iphone16pro":
   rasm=cv2.imread("16pro.webp")
   cv2_imshow(rasm)
   return "narxi 1350$"
 elif rusumi=="iphone11":
   rasm=cv2.imread("11.webp")
   cv2_imshow(rasm)
   return "narxi 280$"
 elif rusumi=="iphone12":
   rasm=cv2.imread("12.webp")
   cv2_imshow(rasm)
   return "narxi 320$"
 elif rusumi=="iphone13":
   rasm=cv2.imread("13.webp")
   cv2_imshow(rasm)
   return "narxi 490$"
 elif rusumi=="iphone15pro":
   rasm=cv2.imread("15pro.webp")
   cv2_imshow(rasm)
   return "narxi 1000$"
 elif rusumi=="iphone15":
   rasm=cv2.imread("15.webp")
   cv2_imshow(rasm)
   return "narxi 900$"
rusumi=input("iphone rusumi:")
natija=narxi(rusumi)
print(natija)